name:                deruta
version:             0.1.0.0
github:              "genya0407/deruta"
license:             MIT
author:              "Yusuke Sangenya"
maintainer:          "longinus.eva@gmail.com"
copyright:           "2018 Yusuke Sangenya"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/genya0407/deruta#readme>

dependencies:
- base >= 4.7 && < 5
- feed == 1.*
- time == 1.*
- text == 1.*
- xml-conduit == 1.*
- xml-types == 0.3.*
- scotty == 0.11.*
- transformers == 0.5.*
- tagsoup == 0.14.*
- http-conduit == 2.3.*
- yaml == 0.8.*

data-dir: data
data-files: files/*.xml

library:
  source-dirs: src

executables:
  deruta-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deruta

tests:
  deruta-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deruta
